engineyard/ey-cookbooks-stable-v6

- cookbooks/mysql/recipes/extras.rb
- cookbooks/postgresql/recipes/setup_app_users_dbs.rb
- cookbooks/reboot/templates/default/rc.local.erb
Updates the rc.local script to ensure v6 instances do a full Chef run, in response to missing /var/run/engineyard preventing Unicorn starting up if an instance is restarted multiple times consecutively.
Also updates MySQL extras recipe to use password as former no password method fails on post restart run.
Also updates PostgreSQL setup_app_users_dbs recipe to use localhost for the DB hostname on instances running DBs, as hostname from DNA does not yet resolve to updated private IP that soon after instance restart and thus access is blocked by AWS SG. On other instances it still resolves to host from DNA in order that it works with RDS still.
Some QA already done, tested on solo (both EIP and public hostname) and multi instance environments, with Unicorn and Passenger and latest MySQL and …
> Updating reboot script to ensure full Chef run on v6

- cookbooks/ey-lib/libraries/ey-environment.rb
-------------
Update the patch versions of the supported Rubies.
-------------
Make the latest Ruby versions available.
Estimated risk
-------------
Medium. Only the patch versions of Ruby got bumped.
-------------
ey-environment library: `default_ruby_version` function
-------------
Booted an environment with the following Ruby versions (sequentially) 2.3, 2.4, 2.5, 2.6.
Checked if it booted and applied correctly and deployed successfully.
Checked if the correct (and latest) ruby version got installed and used.
-------------
N/A
> [FB-493] Update Ruby versions

- cookbooks/collectd/files/default/check_readonly.sh
- cookbooks/collectd/files/default/mounts_ro_ignore
- cookbooks/collectd/recipes/default.rb
-------------
This PR fixes alerts with the message "The device mounted at /snap/core/7270 is read only".
It does so by defining file-system mountpoint patterns that should be ignored by this check.
Those patterns currently are:
```
/snap
/run/user
/proc
/sys
```
If a mountpoint (e.g. `/snap/core/7270`) is read-only, but matches one of the patterns, it is not reported.
-------------
Fix false read-only mounts alerts.
Estimated risk
-------------
Medium. Only the `check_readonly.sh` script has been changed. We need to make sure though, that no "real" alerts will be ignored.
-------------
collect recipe - `check_readonly.sh` script
-------------
1. Booted a solo env (Ruby app, testing stack …
> [FB-552] Add ignore logic to check_readonly script

- cookbooks/ruby/recipes/default.rb
Fixes issues with preview versions like 2.7.0-preview1. Prevents installing ruby if it's already installed.
> Check if bin/ruby exists instead of ruby -v

- cookbooks/postgresql/attributes/version.rb
- cookbooks/postgresql/recipes/server_install.rb
- cookbooks/postgresql/templates/default/install.sh.erb
Use apt install to install .deb files
Upgrade Postgresql to 10.9 and 11.4
Upgrade Postgresql to 10.9 and 11.4
High
Postgresql
1. Boot an environment with Postgresql 10. Check that Postgresql 10.9 is running.
2. Boot an environment with Postgresql 11. Check that Postgresql 11.4 is running.
Note: If you're upgrading an existing environment or booting an environment using a snapshot, make sure "Prevent database version changes" is not checked to get the latest versions.
> Use apt install and Upgrade Postgresql

- cookbooks/packages/recipes/default.rb
- custom-cookbooks/packages/cookbooks/custom-packages/attributes/default.rb
Add allow_downgrades to packages recipe
https://t3.fogbugz.com/f/cases/635
Add allow_downgrades to packages recipe to install old versions of packages
Low
Packages custom recipe
Install the latest imagemagick package (apt-get install imagemagick)
Enable custom packages recipe.
Add `{'name' => 'imagemagick', 'version' => '8:6.9.7.4+dfsg-16ubuntu6', 'allow_downgrades' => true}` to custom-packages/attributes/default.rb
Check that imagemagick is downgraded.
> [FB-635] Add allow_downgrades to packages recipe

- cookbooks/haproxy/templates/default/haproxy.cfg.erb
Assume HTTP 401 as healthy on HAproxy healthcheck 
HAproxy is now accepting HTTP 401 return as a healthy check
Low
HAproxy
Boot environment
Deploy TODO app and use basic authentication (https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/)
Verify that HTTP 401s are returned from nginx to HAproxy and that HAproxy is marking app instances as healthy
> [FB-576] Assume HTTP 401 as healthy on HAproxy healthcheck

- cookbooks/passenger5/recipes/install.rb
- cookbooks/ruby/files/default/gemrc
- cookbooks/ruby/recipes/default.rb
- cookbooks/ruby/recipes/rubygems.rb
Remove --no-ri --no-rdoc from recipes
Here's the description from the v5 PR
> Remove --no-ri --no-rdoc
> Add /root/.gemrc with --no-ri --no-rdoc --no-document
> Note: .gemrc having --no-ri --no-rdoc on rubgyems 3 and --no-document on rubygems 2 is not a > problem. gem commands won't fail. gem install will only fail with --no-ri --no-rdoc on rubygems 3 > if you use the flags on the command line NOT on .gemrc
https://github.com/engineyard/ey-cookbooks-stable-v5/pull/398
> Add /root/.gemrc with --no-document

- cookbooks/ey-cron/recipes/default.rb
Applies correct ownership settings to user's crontab file. Fixes https://github.com/engineyard/ey-cookbooks-stable-v6/issues/118
Applies correct ownership settings to user's crontab file
Low
ey-cron
Add cronjob through UI and through custom-cron chef recipe. 
Test for both root and deploy user
Verify that chef-run completes successfully and no errors appear in logs
Verify that cronjobs are added accordingly
> Apply correct ownership settings to user's crontab file

- cookbooks/postgresql/attributes/version.rb
- cookbooks/postgresql/recipes/server_install.rb
-------------
Update to the latest available patch versions of PostgreSQL 9.5 and 9.6.
-------------
Upgrade to PostgreSQL 9.5.18 and 9.6.14.
Estimated risk
-------------
Low. These are just patch version bumps.
-------------
postgresql cookbook.
-------------
0. Created a testing stack with the changes of this PR.
1. Created, Booted, and deployed Ruby environments (solo, PG 9.5 and staging, PG 9.6)
2. Verified if the app work.
3. Verified if the installed PostgreSQL versions are 9.5.18 and 9.6.14 respectively.
-------------
Test patch version upgrades and downgrades of PG 9.5 and 9.6.
> [FB-741] Bump PostgreSQL 9.5 and 9.6 versions

- cookbooks/app/recipes/create.rb
- cookbooks/env_vars/recipes/init.rb
Adding an empty env.custom file when no recipe custom-env_vars is not used
Adds an empty env.custom file in cases where no custom variables are set
Low
Unicorn
Boot env with QA stack.
Make sure that there are no chef/deploy errors
Add env variables through dashboard. Make sure that they are added successfully.
Use custom-env_vars recipe to add custom variables. Make sure that they are added successfully.
> Always create env.custom, even an empty one

- cookbooks/collectd/recipes/httpd.rb
Enable fcgiwrap.socket on instance start.
Fixes performance graphs' unavailability after instance reboot
Low
Collectd
Boot QA stack using all type of instance (app_master + app + db_master + db_slave + util)
Verify that performance graphs are available for any instance
Restart each one via dashboard
Clear cookies & cache on browser
Visit performance graphs page for each instance, verify that no error occurs
Log into each instance, run `systemctl status fcgiwrap`, confirm status is `active (running)`
> Enable fcgiwrap.socket on instance start.

- custom-cookbooks/shared_db/README.md
- custom-cookbooks/shared_db/cookbooks/ey-custom/metadata.rb
- custom-cookbooks/shared_db/cookbooks/ey-custom/recipes/after-main.rb
- custom-cookbooks/shared_db/cookbooks/shared_db/README.md
- custom-cookbooks/shared_db/cookbooks/shared_db/attributes/default.rb
- custom-cookbooks/shared_db/cookbooks/shared_db/metadata.rb
- custom-cookbooks/shared_db/cookbooks/shared_db/recipes/default.rb
Adds `shared_db` custom recipe
Adds shared_db recipe to allow two applications to share a single database.yml configuration file
Low
New recipe
Boot QA stack
Add a second application on the QA environment
Enable recipe
Verify that keep.database.yml file is created and each app's database.yml is a sym link to parent app's database.yml
> Adding shared_db custom recipe

- cookbooks/collectd/recipes/default.rb
Removes RRD data inherited by AMI
Fixes performance graphs on newly booted stack V6 recipes 
Low
Collectd recipe
Boot QA stack
Verify that performance graphs work
Verify that there is only one directory under /var/lib/collectd/rrd and it's named after the current private hostname of the instance
> [FB1220] Remove rrd dirs of non-existent private hostnames

- cookbooks/mysql/templates/default/check_mysql.sh.erb
Fix /engineyard/bin/check_mysql.sh used by collectd.
Update script used by collectd for mysql replication checks.
Low
Collectd
1. Boot a mysql environment with a db replica.
2. Check that mysql replication check does not fail.
> [FB-1352] Add -d on read

- cookbooks/ec2/recipes/default.rb
Run e2fsck to fix issues when using snapshots to boot instances.
Run filesystem check to fix issues when using snapshots to boot instances.
Low
Volume setup
1. Boot an environment with an application master.
2. Boot an app instance using a snapshot.
3. The instance should be green.
> [FB-582] Run e2fsck before mounting /data

- cookbooks/nodejs/recipes/yarn.rb
PR to fix issues found while QAing https://github.com/engineyard/ey-cookbooks-stable-v6/pull/132
File _/etc/apt/sources.list.d/yarn.list_ was populated as such:
```
deb      https://dl.yarnpkg.com/debian/ bionic stable main
```
while the following was expected:
```
deb      https://dl.yarnpkg.com/debian/ stable main
```
> Fixing distribution name

- cookbooks/passenger5/recipes/monitoring.rb
-------------
Change the default passenger memory limit from `800MB` to `250MB`
-------------
Through this PR, the current default memory limit of `800MB` for `passenger-v5` would be reverted back to `250MB`
Estimated risk
-------------
Security Risk not applied. The number of possible worker limit would get increased for each instance
-------------
`passenger-5` cookbook
-------------
1. Boot a new instance under new stack version (In my case custom made one with the branch of applied changes to passenger-5)
2. Check the current memory limit by studying `crontab -e`, regarding the memory about defined as a parameter of `/engineyard/bin/passenger_monitor`
-------------
1. …
> [FB-652] Changing the Default Memory Limit to 250MB

- cookbooks/collectd/recipes/default.rb
-------------
This PR introduces a more sane handling of duplicate RRD data directories and ensures, that only one data directory exists.
-------------
Fixes an issue with missing performance metrics.
Estimated risk
-------------
Medium. Messes with RRD data directories on-the-fly
-------------
collectd recipes
Dependencies
-------------
None
-------------
0. Created a testing stack with the changes in this PR.
1. Booted an environment and checked if everything works.
2. Checked if performance metrics are consistently shown.
3. Checked if only the current instance data is stored inside `/var/lib/collectd/rrd`.
4. Ran apply and checked if everything keeps working.
5. Manually added RRD data …
> [FB-917] Fix handling of multiple RRD data directories in collectd

- cookbooks/postgresql/recipes/server_configure.rb
-------------
This PR adds a code block which writes the db lock file for PostgreSQL on the first cookbooks run. This is necessary to ensure that the lock file is present on any db snapshot which could subsequently be used to boot a db slave.
-------------
Enhances the PostgreSQL recipes to write the DB version lock file on the initial cookbooks run.
Estimated risk
-------------
Medium. Existing behaviour should not be adversely affected. Still it touches an important area.
-------------
postgresql recipes
Dependencies
-------------
None
-------------
Created a testing stack with the changes in this PR.
Booted an environment (PG 11, lock db version set, production configuration).
Checked if …
> [FB-728] Lock db version file not written during the first cookbooks run with PG

- cookbooks/ruby/recipes/default.rb
- cookbooks/ruby/recipes/dependencies.rb
-------------
This PR reverts using `ruby-install` to also install dependencies for Ruby. It incorrectly handles dependencies for Ruby 2.3 which requires an older version of OpenSSL.
-------------
Fixes Ruby 2.3 installation issues.
Estimated risk
-------------
Low. We revert back to how we handled Ruby dependencies previously.
-------------
Ruby recipes
Dependencies
-------------
None
-------------
TC 1
1. Created a testing stack with the changes in this PR.
2. Booted an environment with a Ruby app using Ruby 2.3.
3. Deployed the app and checked if it works.
4. Manually tested the openssl gem on the instance.
TC2
1. Created a testing stack with the changes in this PR.
2. Booted an …
> [FB-1999] Fix OpenSSL dependency for Ruby 2.3

- cookbooks/collectd/recipes/httpd.rb
Start and enable collectd httpd
Start collectd httpd after a reboot
Low
Collectd
1. Boot an environment.
2. Reboot the solo or app master.
3. Check that collectd-httpd is running `systemctl status collectd-httpd`
> [FB-1257] Start and enable collectd httpd

- cookbooks/ey-lib/libraries/env_vars.rb
-------------
This PR removes old code that wasn't used from the environment variables cookbooks helpers.
-------------
Cleans up old code around environment variables.
Estimated risk
-------------
Low. Carefully checked that nothing still references the removed portions of code.
-------------
ey-lib recipes, EnvVars helper module
Dependencies
-------------
None
-------------
* TC 1
- Booted an environment with this change and the `EY_REDIS_ENABLED` variable set.
- Checked if the variable behaves as expected.
* TC 2
- Booted an environment with this change and the variable `MY_TEST_VAR=42` set.
- Checked if everything works.
- Checked if variable was set correctly. …
> [FB-943] Remove env var encrypt decrypt code from cookbooks

- cookbooks/nginx/templates/default/nginx-plusplus.conf.erb
This patch adds all 3 private network ranges to the list of IPs that nginx's considers as trusted sources to extract the real IP of client from
Fixes logging of the real IP on custom networks (VPCs)
Low
nginx
none
Boot QA stack
Verify that chef run / deployment finishes successfully
Verify that the real IP of the client is being logged
Use HTTP/HTTPs traffic to test
Verify on solo / multi instance envs
Use different VPCs (with different CIDRs) to verify
> [FB2006] Logging the real IP on custom networks CIDR on NGINX

- cookbooks/delayed_job4/templates/default/dj.erb
- cookbooks/resque/files/default/resque
Sourcing environment variables on `DJ` and `resque` scripts
Sourcing environment variables on `DJ` and `resque` scripts
Low
Delayed Jobs & Resque
none
Use `/etc/init.d` scripts for `resque` and `DJ` to verify that jobs can be stoped/restarted/started 
Use monit to restart background jobs, verify that no issue exists
> [FB1935] Sourcing env vars in background workers

- cookbooks/ntp/recipes/default.rb
Instructing systemd to start `ntp` service on chef run
NTP service is now started after an instance reboot
Low
NTP recipe
none
Boot QA stack
Verify that ntp service is running: `systemctl status ntp`
Reboot instance
Verify that ntp service is running: `systemctl status ntp`
> [FB-1933] Starting NTP service on chef run

- cookbooks/env_vars/templates/default/env.cloud.erb
-------------
Fixes the env_var cookbook which generates the variables for the environment from the EngineYard UI
-------------
Fixed PHP environmental variables
Estimated risk
-------------
High. Its a main cookbook and its run on ever instance however currently PHP is unable to start if environment variables are set 
-------------
Booted multiple environments one PHP and one Ruby
Set custom variables on both instances
Pressed Apply
Checked that the correct variable was created
-------------
Boot up an environment of your choice. Ruby, PHP, or NodeJS
Set `Environment Variables` via the EngineYard UI
Press apply
Make sure the application server process is able to start and there are no errors, …
> [FB-873] fixes php environmental variables [ZD-160560]

- cookbooks/ey-lib/libraries/ey-environment.rb
-------------
This PR adds support for Ruby 2.7.
-------------
Adds support for Ruby 2.7.
Estimated risk
-------------
Low. Only new Ruby version added. Nothing existing was modified.
-------------
ey-lib recipes. Specifically, the `default_ruby_version` function.
Dependencies
-------------
Needs to be released with AMIs: `ey-ubuntu-18.04.0.9` (https://github.com/engineyard/ey-stable-v6-infrastructure/releases/tag/ami-v0.9)
Needs to be released **after** the following has been released:
* https://jira.devfactory.com/browse/EYPP-12375
* https://jira.devfactory.com/browse/EYPP-12376
-------------
On a staging cloud (buckman) with the backend changes deployed and the `ruby_270` feature flag …
> [FB-2137] Add Support for Ruby 2.7

- EnvironmentVariables.md
- cookbooks/ey-lib/libraries/env_vars.rb
- cookbooks/ey-lib/libraries/ey-environment.rb
- cookbooks/php/attributes/php.rb
- cookbooks/php/files/default/php7.4.ini
- cookbooks/php/libraries/php_helpers.rb
- cookbooks/php/recipes/configure.rb
- cookbooks/php/recipes/default.rb
- cookbooks/php/recipes/fpm.rb
- cookbooks/php/recipes/install.rb
- cookbooks/php/spec/configure_spec.rb
- cookbooks/php/spec/default_spec.rb
- cookbooks/php/spec/install_spec.rb
- spec/Gemfile
- spec/Gemfile.lock
-------------
This PR allows installing additional PHP extensions by setting an environment variable.
-------------
Adds the `EY_PHP_EXTRA_EXTENSIONS` environment variable for installing extra PHP extensions.
Estimated risk
-------------
Medium. No existing logic was modified.
-------------
PHP recipes
Dependencies
-------------
Depends on #162 
-------------
With a testing stack with the changes of this PR:
1. Created a PHP application
2. Created an environment (PHP 7.3, PostgreSQL)
3. Set the environment variable `EY_PHP_EXTRA_EXTENSIONS="redis  ,  amqp "`
4. Booted the environment in a solo configuration
5. Checked that env boots correctly, apply and deployment are successful, and the …
> [TEY-96] Install extra PHP extensions via an environment variable 

- cookbooks/delayed_job4/templates/default/dj.erb
-------------
This patch updates the `start-stop-daemon` argument to be Ubuntu compatible for setting the user as which the DJ process is spawned.
-------------
Ensures the Delayed Job processes are run as the application owner user rather than the root user.
Estimated risk
-------------
Low - a single argument change.
-------------
Main delayed_job_4 recipe.
-------------
Changed the argument from `-u` to `-c` directly in the `/engineyard/custom/dj` on an existing v6 instance and restarted DJ via Monit.
-------------
Boot a v6 instance or cluster and enable the custom-delayed_job4 recipe so that DJ is set to run on an instance. Ensure the `ruby …
> [FB-2510] Ensures DJ spawns as deploy

- cookbooks/ey-core/recipes/swap.rb
-------------
This PR adds an extra sleep before calling `mkswap` to prevent a potential race condition.
-------------
Fixes a potential swap creation issue.
Estimated risk
-------------
Low. Just added a sleep command.
-------------
ey-core recipes, swap.rb
Dependencies
-------------
None
-------------
1. Created a dev stack with the changes in this PR.
2. Created and booted an environment.
3. Checked if everything works.
4. Logged into the instance and checked if the swap partition was created (`free`).
5. Checked the swap creation trace log in `/var/log` and verified if it behaved as expected.
-------------
* Test a PHP app.
* Test different environment configurations.
> [FB-2181] Add extra sleep before mkswap

- custom-cookbooks/snaps-removal/README.md
- custom-cookbooks/snaps-removal/cookbooks/custom-snaps-removal/README.md
- custom-cookbooks/snaps-removal/cookbooks/custom-snaps-removal/attributes/default.rb
- custom-cookbooks/snaps-removal/cookbooks/custom-snaps-removal/files/default/snaps_remove.sh
- custom-cookbooks/snaps-removal/cookbooks/custom-snaps-removal/metadata.rb
- custom-cookbooks/snaps-removal/cookbooks/custom-snaps-removal/recipes/default.rb
- custom-cookbooks/snaps-removal/cookbooks/ey-custom/metadata.rb
- custom-cookbooks/snaps-removal/cookbooks/ey-custom/recipes/after-main.rb
This custom recipe can be used to unmount and remove any mounted snaps posing security risks.
Adds a new custom recipe to unmount and remove snaps.
Low
This is a new recipe
none
Boot solo and multiple app env
Ensure chef is ran successfully
Verify that there are no snaps mount use `df -h` to verify
Leave the environment running for a few days
Verify that chef runs successfully
Reboot instances, verify that chef runs successfully
Stop/start instances, verify that chef runs successfully
> [FB-1437] Adding custom recipe snaps-removal

- cookbooks/nginx/templates/default/nginx_app.conf.erb
-------------
This PR changes the nginx config to redirect assets to the ssl app stream when ssl is enabled.
-------------
Redirects assets to ssl app stream when ssl is enabled
Estimated risk
-------------
Low. Just a minor change in the nginx config.
-------------
nginx recipes
Dependencies
-------------
None
-------------
1. Booted a Ruby staging environment (Unicorn) with the changes in this PR.
2. Configured SSL for the environment.
3. Checked if it applies correctly, deploy succeeds, and app works.
4. Checked if the nginx ssl config file redirects to the ssl app stream in both try_files directives.
-------------
Test different app servers (passenger).
Test a PHP app.
> [TEY-147] Redirect assets to ssl app stream when ssl is enabled

- cookbooks/collectd/files/default/check_health_for
- cookbooks/collectd/files/default/check_readonly.sh
- cookbooks/postgresql/templates/default/check_postgres_wrapper.sh.erb
-------------
This PR sets an appropriate umask in the collectd check scripts. This avoids wrong permissions on check directories in /tmp.
-------------
Fixes incorrect permissions of directories created by collectd check scripts
Estimated risk
-------------
Low. Just umask statements added to check scripts.
-------------
collectd recipes, postgresql recipes
Dependencies
-------------
None
-------------
Booted multiple environments and checked if the check directories were created with correct permissions.
-------------
Test with a MySQL database.
Test a PHP app.
> [TEY-151] Explicitly set umask in collect check scripts

- cookbooks/nginx/recipes/default.rb
- cookbooks/nginx/templates/default/customer_ssl_cipher.erb
- cookbooks/nginx/templates/default/default_ssl_cipher.erb
- cookbooks/nginx/templates/default/nginx_app.conf.erb
-------------
Restores loading of dedicated ssl_cipher files in app level nginx config, lost in v5 migration, allowing for customisation of SSL protocols and ciphers by customers.
-------------
Adds support for custom SSL protocols and ciphers for Nginx.
Estimated risk
-------------
Medium - small changes (taken from v5 recipes) to key cookbook impacting all environments regardless of application server stack.
The change in directory for storing ssl_cipher files will leave orphaned files in `/etc/nginx/ssl` It should not impact any customers' custom ssl_ciphers as although the files will be recreated as new under `/etc/nginx/servers` that file will not being called by nginx and so unused.
-------------
Nginx recipe …
> [TEY-157] Restores loading of custom ssl ciphers

- cookbooks/postgresql/files/default/pgdg.list
- cookbooks/postgresql/templates/default/install.sh.erb
-------------
This PR switches the old morgue package repo for PostgreSQL to the new apt-archive repo.
-------------
Improves the installation process for PostgreSQL.
Estimated risk
-------------
Medium. The PostgreSQL install script was changed a lot. But it is now much simpler.
-------------
postgresql recipes
Dependencies
-------------
None
-------------
**TC 1**
1. Booted a Ruby production env with PostgreSQL 11 (with the changes in this PR).
2. Made sure Chef run is successful and app works.
**TC 2**
1. Booted a Ruby production env with PostgreSQL 9.6 from a current stable-v6 stack.
2. Observed that the Chef run fails because of the installation of PostgreSQL doesn't work.
3. Upgraded …
> [TEY-161] Switch PG morgue to new official apt-archive mirror

- cookbooks/app/recipes/build.rb
-------------
This PR fixes the logic for including the recipe `mysql::setup_app_users_dbs`.
-------------
Fixes a bug with configuring Aurora MySQL.
Estimated risk
-------------
Low. Just updated the check for including the recipe.
-------------
app recipes
Dependencies
-------------
None
-------------
1. Booted a new environment with an Aurora MySQL 5.6 database.
2. Verified that the deploy fails because the mysql DB user wasn't set up.
3. Upgraded to a dev stack with the changes in this PR.
4. Applied and checked if Chef run is successful.
5. Checked if deployment works and app works.
-------------
Test a PHP application
Test with different app servers.
> [TEY-141] Fix logic for including recipe mysql::setup_app_users_dbs

- cookbooks/php/recipes/default.rb
- cookbooks/php/recipes/system_ruby.rb
-------------
This PR installs the OS default Ruby package for a PHP application. This is needed for newer versions of serverside (>= 2.8.0) to work properly.
-------------
Ensures that Ruby is installed even on non-Ruby applications.
Estimated risk
-------------
Low. Just installs the `ruby` OS package.
-------------
php recipes
Dependencies
-------------
None
-------------
1. Tested upgrading an existing PHP environment and verified that the deploy issue with serverside 2.8.0 is fixed.
2. Tested booting a new PHP environment and verified that the Chef run completes successfully and the app deploys successfully with serverside 2.8.0.
-------------
Test a Ruby application. …
> [TEY-181] Install the system Ruby for PHP applications

- cookbooks/ey-init/recipes/integrate.rb
-------------
Ensures that db-ssl certificates are copied out to new instances from the DB master instance on the post-integration quick run. These were previously failing for MySQL environments.
-------------
Fixes an issue where DB SSL certificates were not put in place on new instances in MySQL environments.
Estimated risk
-------------
Low - is a simple change to make applicable block in recipe identical to functioning v5 recipe.
-------------
Main chef, `ey-init` (quick chef run) recipe.
Dependencies
-------------
None.
-------------
Without the fix:
* Added a utility instance
* Confirmed that integration completed and quick chef ran on the DB master
* Checked that …
> [TEY-207] moves db-ssl recipe call outside of postgres if statement

- cookbooks/mysql/recipes/default.rb
- cookbooks/mysql/templates/default/my.conf.erb
-------------
This PR disables binary logging on solo environments where binary logging is unnecessary. In earlier MySQL versions, binary logging was disabled by default and was enabled if we specified the --log-bin option. From MySQL 8.0, binary logging is enabled by default, whether or not we specify the --log-bin option. 
-------------
Disables MySQL binary logging for solo environments.
Estimated risk
-------------
Low. Adds `skip-log-bin` parameter to the MySQL configuration file.
-------------
MySQL 8.0
Dependencies
-------------
None
-------------
MySQL 5.6 on a solo environment.
MySQL 5.7 on a solo environment.
MySQL 8.0 on a solo environment.
MySQL 8.0 on a clustered environment …
> [TEY-197] Disable binary logging on solo environments

- cookbooks/passenger5/recipes/install.rb
-------------
Reverts the change made in https://github.com/engineyard/ey-cookbooks-stable-v6/commit/9506fe2125333b311781f4aabc2e89e244a45bf5#diff-71d9b77ecb60306bb60530e8069e0080 that made the passenger variables lazy in order to get around pre-swap calculation but resulted in multi-app envs having the same passenger port set.
-------------
Reverts a regression introduced in the last release regarding the ports used for Passenger on multi-app environments.
Estimated risk
-------------
Low - reversion of recipe to previous state.
-------------
Passenger recipe.
-------------
None.
-------------
None required.
> [TEY-218] Reverts change of Passenger variables to lazy

- custom-cookbooks/sidekiq/cookbooks/custom-sidekiq/README.md
-------------
Updates the custom-sidekiq readme to correct the way the instance name is specified in the deploy hook from a non-working symbol to a working string.
Also adds to the readme the requirement to use the redis-namespace gem.
-------------
None needed.
Estimated risk
-------------
Zero, is just a readme change.
-------------
The custom_sidekiq recipe.
-------------
Re-read the README.
-------------
None needed.
> [FB-3946] Update custom-sidekiq README

- cookbooks/elasticsearch/recipes/start.rb
Fixes restart issue with ElasticSeach when apply is ran
Fixes restart issue with ElasticSearch
Medium risk - ElasticSearch currently can cause downtime when chef is running
ElasticSearch
ElasticSearch
* Created Elasticsearch instance
* Checked ES was running using systemctl
* Pressed apply
* Checked if ES had restarted
* Booted up completely new environment and instance using ES
* Made sure ES had started after boot
* Pressed apply
* Made sure ES hadn't restarted
**QA instructions**
* Create environment
* Set up ElasticSearch
* Press apply once after ElasticSearch is successfully running
* Check if ElasticSearch has been restarted
> [FB-3899] Fixes ElasticSearch restarting on apply

- EnvironmentVariables.md
- cookbooks/nodejs/attributes/default.rb
Allows NodeJS to be set by environmental variable 
NodeJS can now be easily set by environmental variable
Low risk - Adding ease of use to v6 rather than overlaying chef .
NodeJS
NodeJS
* Booted an instance
* Set version by UI, after UI set by variable, and meta. Made sure version would change and set variable to be default value if set
* Boot an environment up (any setting)
* Set NodeJS by backend, followed by running an apply
* Check it installed on instance(s)
* Set NodeJS by variable, follow by running an apply
* Check the variable version is installed on the instance
* Remove nodeJS variable, set version either by …
> [FB-3873] Allows NodeJS to be set easily by variables

- cookbooks/mysql/recipes/install.rb
- cookbooks/mysql/templates/default/copycerts.sh.erb
- cookbooks/ssh_keys/recipes/default.rb
Small but very needed addition to MySQL and SSH_KEYS to allow certificate files to be pulled before the integration step on new instances, SSH_KEYS allow all instances with-in VPC access to SSH if the key is in place rather than specific private IP addresses.
Fixes integration and need of manual input when adding additional application servers when using MySQL certificates 
High risk - Can cause instance to not function correctly due to SSH_KEYS no longer working with the internal key or MySQL certificates being incorrectly copied.
ssh_keys, mysql
ssh_keys, mysql
* Added instance to set up that was already running
* Set …
> [FB-2828] MySQL certificate files missing on new instance boot

- cookbooks/unicorn/recipes/monit_monitoring.rb
This is a small patch to fix unicorn.rb not overwriting with new values
Unicorn.rb takes new values on apply if they're set
High risk - Can cause unicorn not to configure if recipe is incorrect
unicorn
unicorn
* Changed values on an environment and hit apply
* Set up environment with custom worker values - Check unicorn.rb values
* Change custom worker values to default or something else - Check unicorn.rb values
* Boot up new environment - Check unicorn.rb has been configured correctly to values for that type of instance / settings
> [FB-2827] Fixes unicorn.rb not overwriting correctly

- cookbooks/ey-lib/libraries/app_server_configs.rb
This is a small patch to fix the default memory of passenger workers along with fixing the monitoring script
Changed default value of passenger to 250 rather than 255
Medium risk - Can cause instance to not function correctly if passenger isn't monitored correctly  
ey-lib
ey-lib
* Booted up new environment under passenger with default value
* Set up environment with custom worker memory values - Check script runs correctly
* Change custom worker memory values to default - Check script runs correctly 
* Boot up new environment - Check script runs correctly
> [FB-2826] Address default passenger memory limit

- cookbooks/puma/templates/default/app_control.erb
Changes --control to --control-url in puma startup.
The --control option has been removed in puma 5
Add support for puma 5 ?
Low, requires puma 3.12.0 / 2018-07-13
puma
None
none
> [FB-3894] Update puma startup to use --control-url

- cookbooks/ssh_keys/recipes/default.rb
Docker instances have multiple ethernet interfaces so the script needed updated to identify the physical ethernet adapter. Physical ethernet interfaces have a txqueuelen > 0. This update fixes the entry in authorized_keys and allows deployments to succeed.
> Fix generated ssh authorized_keys file on docker instances

- cookbooks/postgresql/templates/default/install.sh.erb
-------------
Installs the PostgreSQL additional modules on postgres_95 and postgres_96 databases.
-------------
Installs the PostgreSQL additional modules on PostgreSQL 9.5 and PostgreSQL 9.6 databases. 
Estimated risk
-------------
Low
-------------
postgres_95, postgres_96, postgres_10, postgres_11
-------------
This has been tested with postgres_95, postgres_96, postgres_10, postgres_11.
-------------
* Boot postgres_95 environment(It can be a solo or a clustered environment). 
* Enable hstore extension
```
cat << EOF > /db/postgresql/extensions.json     
{
"database_name": ["hstore"]
}
EOF
```
* Run chef
* Check if it was enabled
```
psql <database_name> -c "\dx"
```
* …
> [FB-5080] Install PostgreSQL additional modules

- cookbooks/mysql/recipes/install.rb
-------------
Database SSL push does not apply to RDS environments.
-------------
Skip database SSL push on RDS environments
Estimated risk
-------------
Low
-------------
MySQL cookbook
-------------
Tested on mysql_5x, no_db, and amazon_rds environments
-------------
1. Boot mysql_5x environment
2. Make sure the chef is successful and the environment is green
1. Boot no_db environment
2. Make sure the chef is successful and the environment is green
1. Boot amazon_rds environment
2. Make sure the chef is successful and the environment is green
> [FB-5013] Skip database SSL push on RDS environments

- cookbooks/thinking_sphinx_3/README.md
- cookbooks/thinking_sphinx_3/attributes/default.rb
- cookbooks/thinking_sphinx_3/metadata.rb
- cookbooks/thinking_sphinx_3/recipes/cleanup.rb
- cookbooks/thinking_sphinx_3/recipes/default.rb
- cookbooks/thinking_sphinx_3/recipes/install.rb
- cookbooks/thinking_sphinx_3/recipes/setup.rb
- cookbooks/thinking_sphinx_3/recipes/thinking_sphinx.rb
- cookbooks/thinking_sphinx_3/templates/default/after_restart.erb
- cookbooks/thinking_sphinx_3/templates/default/sphinx.monitrc.erb
- cookbooks/thinking_sphinx_3/templates/default/thinking_sphinx.yml.erb
- custom-cookbooks/thinking_sphinx_3/README.md
- custom-cookbooks/thinking_sphinx_3/custom-thinking_sphinx_3/README.md
- custom-cookbooks/thinking_sphinx_3/custom-thinking_sphinx_3/attributes/default.rb
- custom-cookbooks/thinking_sphinx_3/custom-thinking_sphinx_3/metadata.rb
- custom-cookbooks/thinking_sphinx_3/custom-thinking_sphinx_3/recipes/default.rb
- custom-cookbooks/thinking_sphinx_3/ey-custom/metadata.rb
- custom-cookbooks/thinking_sphinx_3/ey-custom/recipes/after-main.rb
-------------
Thinking Sphinx cookbooks for stack-v6. Involves customized installation of `sphinxsearch` and configuration on Ubuntu based v6 distribution.
-------------
Adds Thinking Sphinx integration to Stack-v6
Estimated risk
-------------
Low, This is a feature. 
-------------
`Thinking_Sphinx_3` cookbook and `Custom-Thinking_Sphinx_3` cookbook
Dependencies
-------------
None
-------------
1. Booted a multi-environment with a `util` instance named `sphinx`
2. Used custom ThinkingSphinx3 cookbook and setup installation within the util instance.
3. Re-deployed the application
4. Verified if Thinking Sphinx workers are running.
-------------
**Scenario 1**
1. Boot a solo …
> [FB-3883] Thinking Sphinx 3

- cookbooks/ey-cron/recipes/default.rb
Fixes missing path in crons on non ruby environment 
Fix for path missing in crons
High risk - certain crons fail as the path to certain binaries aren't set. 
ey-cron
ey-cron
* Create v6 environment 
* Set UI crontabs
* Triggered apply
* Checked PATH was set under crontab
**QA instructions**
* Create v6 environment 
* Set a custom cron task by UI or cookbooks
* Check that PATH exists with in cron
> [FB-3923] Fix cron path on non ruby environments 

- cookbooks/ephemeraldisk/libraries/ephemeral_helpers.rb
Fixes the instance reboot issue where it will refuse to start or start in maintenance mode.
Fixes fstab formatting for ephemeral disks
Medium risk - Without a fix instances with ephemeral disks mounted can not safely be restarted without manual intervention afterwards
ephemeraldisk
ephemeraldisk
* Reboot an instance with ephemeral disks mounted
* Boot an instance which utilises ephemeral disk
* SSH into instance
* Make sure its mounted using `df -h`
* Check fstab `cat /etc/fstab` 
* Make sure its mounted with nofail
* Reboot instance
* Ensure instance restarts correctly
> [FB6657] ephemeraldisk recipe update to avoid reboot failures

- cookbooks/openssl/recipes/default.rb
-------------
1. Adds `ca-certificates` package to chef to keep certificates up to date
-------------
Updated system certificates
Estimated risk
-------------
Moderate/High - Is required to avoid errors with external sources using X1 LetsEncrypt
-------------
1. `openssl` chef recipe 
Dependencies
-------------
None
-------------
* Created environment
* Booted up solo instance
-------------
* Create environment under postgres
* Boot up instances either solo or multi-instances
* Ensure chef runs correctly and entirely
> Adds ca-certs to the recipes

- cookbooks/haproxy/README.md
- cookbooks/haproxy/recipes/configure.rb
-------------
PR adds environment variable "EY_HEALTHCHECK_DOMAIN_OVERRIDE" to be use by haproxy recipe
FBZ : https://t3.fogbugz.com/f/cases/10372/
-------------
Adds "EY_HEALTHCHECK_DOMAIN_OVERRIDE" which can be used to tel haproxy which domain to use for health-checks if the nginx vhost entry contains multiple entries or if the first entry contains wildcard/regex
Estimated risk
-------------
Low
-------------
Environment Variables/Chef
Dependencies
-------------
NA
-------------
Tested to verify recipe uses the domain set in environment for health-checks
-------------
Recipe required environment variables set
1. EY_HEALTHCHECK_DOMAIN_OVERRIDE : to a valid domain hosted on …
> [FBZ-10372] env var to override invalid HAProxy vhosts

- cookbooks/mysql/recipes/install.rb
-------------
This patch fixes the typo in MySQL 5.7.26 URL
-------------
Estimated risk
-------------
Low
-------------
Chef
Dependencies
-------------
NA
-------------
Tested in #184956
-------------
NA
> FB-10345 Fix MySQL 5.7.26 URL Typo

- custom-cookbooks/sidekiq/cookbooks/custom-sidekiq/README.md
-------------
adding missing config for multiple queues per worker (same as v5)
-------------
document multiple queues per worker
Estimated risk
-------------
low (readme change)
-------------
na
-------------
no testing required, only readme changed, usage already proven to work in customer zd ticket https://engineyard.zendesk.com/agent/tickets/183126
-------------
no QA required
> [FB-10196] adding missing config for multiple queues per worker

- cookbooks/passenger5/templates/default/app_control.erb
This is a fix for the Passenger5 bug documented in FB-10180.
The script in `/engineyard/bin/app_<app_name>` has a bug. It leads to monit looking for the incorrect Passenger PID which results to all attemps at stop/restart failing.
Previous script logic was:
NGINX_PID=`sudo netstat -antp | grep -w '<%= @port %>' | grep LISTEN | awk '{split($7,a,"/"); print a[1]}'`
PASSENGER_PID=`sudo ps -ef | grep passenger-standalone | grep <%= @port %> | awk '{print $2};'`
PIDFILE='/data/<%= @app_name %>/shared/pids/passenger.<%= @port %>.pid'
if [ -n $NGINX_PID ]; then
if [ ! -z $PASSENGER_PID ]; then
if [ ! -f $PIDFILE ]; then
echo $PASSENGER_PID > $PIDFILE
echo "Passenger: PIDFILE $PIDFILE was recreated with PID $PASSENGER_PID"
fi
else
echo "Passenger: Nginx is running with PID $NGINX_PID, but the …
> [FBZ-10180] Modified the PID being inserted to /data/<app>/shared/pids/passenger.<port>.pid
