engineyard/ey-cookbooks-stable-v6

cookbooks/env_vars/libraries/helpers.rb
cookbooks/ruby/recipes/default.rb

If the environment variable EY_RUBY exists, use it to set the ruby version.

Fetch ruby version from EY_RUBY_VERSION

---

cookbooks/nodejs/attributes/default.rb

Add Nodejs 10
Add Nodejs 10.16.0
Low
Nodejs
1. Choose Nodejs 10 on the Edit Environment page.
2. Click Apply
3. Check that node -v outputs v10.16.0.

[FB-732] Add nodejs 10.16.0

---

cookbooks/env_vars/templates/default/env.cloud.erb

https://t3.fogbugz.com/f/cases/706/stable-v6-Filter-dashboard-environmental-variables-from-env-cloud

Adds filtering for environmental variables to remove EY_ named vars

---

cookbooks/redis/recipes/install.rb
cookbooks/redis/recipes/install_from_package.rb

We need to create redis.conf and redis-server.service before installing the redis package.

Fix issues when installing Redis

---

cookbooks/nginx/templates/default/nginx_app.conf.erb

Removes customer specific config on nginx configuration. Fixes https://github.com/engineyard/ey-cookbooks-stable-v6/issues/117
Removes customer specific config on nginx configuration
Medium. Core component involved
Nginx
Boot puma/passenger/unicorn app. Verify chef/deployment/app is working

Removes customer specific config on nginx configuration

---

cookbooks/redis/recipes/install.rb

-------------
Cosmetic refactoring in setting transparent huge pages in the Redis recipe.
-------------
Code improvements in the Redis recipe.
Estimated risk
-------------
Low
-------------
redis recipe
-------------
Created a testing stack and booted an environment with a Redis utility and EY_REDIS_ENABLED=true.
Checked if it works without errors.
-------------
Test with different environment configurations.

[FB-865] Cleanup setting transparent huge pages in Redis recipe

---

custom-cookbooks/fail2ban/README.md
custom-cookbooks/fail2ban/cookbooks/custom-fail2ban/README.md
custom-cookbooks/fail2ban/cookbooks/custom-fail2ban/attributes/default.rb
custom-cookbooks/fail2ban/cookbooks/custom-fail2ban/metadata.rb
custom-cookbooks/fail2ban/cookbooks/custom-fail2ban/recipes/default.rb
custom-cookbooks/fail2ban/cookbooks/ey-custom/metadata.rb
custom-cookbooks/fail2ban/cookbooks/ey-custom/recipes/after-main.rb

fail2ban custom recipe

---

custom-cookbooks/shared_db/cookbooks/shared_db/recipes/default.rb

PR to fix issues found while QAing https://github.com/engineyard/ey-cookbooks-stable-v6/pull/128
The recipe was ran on DB instances causing chef failures

Run recipe only on solo, app and util instances

---

cookbooks/ey-base/recipes/bootstrap.rb
cookbooks/ey-base/recipes/resin_gems.rb
cookbooks/ey-init/metadata.rb
cookbooks/ey-init/recipes/integrate.rb
cookbooks/ey-stonith/README.md
cookbooks/ey-stonith/files/default/stonith.service
cookbooks/ey-stonith/metadata.rb
cookbooks/ey-stonith/recipes/default.rb
cookbooks/ey-stonith/templates/default/stonith.yml.erb

Add stonith on app instances
Monitor the app master and initiate a takeover if it's not responding
Low
Stonith
1. Boot an environment with an app master and app slave
2. Stop haproxy on the app master
3. Check that the takeover terminates the app master and promote the app slave
4. Check the replacement app slave is green

[FB-121] Stonith

---

custom-cookbooks/papertrail/README.md
custom-cookbooks/papertrail/cookbooks/custom-papertrail/README.md
custom-cookbooks/papertrail/cookbooks/custom-papertrail/attributes/default.rb
custom-cookbooks/papertrail/cookbooks/custom-papertrail/metadata.rb
custom-cookbooks/papertrail/cookbooks/custom-papertrail/recipes/default.rb
custom-cookbooks/papertrail/cookbooks/ey-custom/metadata.rb
custom-cookbooks/papertrail/cookbooks/ey-custom/recipes/after-main.rb

Creates customer papertrail recipe to customise main papertrail
Estimated risk
Low
N/a - Option recipe ey-custom
Add papertrail main to cookbooks as well as this
Add recipe to ey-custom - custom-papertrail to after-main.rb
Run chef
Check rsyslog is running and has the configuration that has been set in  attributes has been loaded.

Custom recipe for papertrail

---

cookbooks/papertrail/README.md
cookbooks/papertrail/attributes/default.rb
cookbooks/papertrail/metadata.rb
cookbooks/papertrail/recipes/default.rb
cookbooks/papertrail/templates/default/log_files.yml.erb
cookbooks/papertrail/templates/default/remote_syslog.initd.erb

Creates papertrail recipe for main as its not been ported over from v5 correctly yet
Papertrail added to v6
Low
N/a - Option recipe ey-custom 
Add recipe to ey-custom 
Run chef
Check rsyslog is running and has the configuration file loaded

Papertrail

---

CONTRIBUTING.md
EnvironmentVariables.md
README.md
cookbooks/memcached/README.md
cookbooks/redis/README.md

-------------
Add documentation for currently supported `EY_` environment variables.
Write contribution guidelines for adding additional `EY_` settings.
-------------
Document settings via environment variables.
Estimated risk
-------------
low - no code changes
-------------
Documentation
Dependencies
-------------
None
-------------
Proof read it.
-------------
Check for typos and missing or incorrect information.

[FB-1602] Document environment variables and contribution guidelines

---

cookbooks/ey-core/recipes/swap.rb

-------------
This PR adds detailed logging to the script that creates the swap partition.
It is written to `/var/log/make-swap-xvdc.log`.
-------------
Adds detailed logging to swap partition creation.
Estimated risk
-------------
Low. Only logging code added.
-------------
ey-core::swap recipe
Dependencies
-------------
None
-------------
1. Booted a new environment with the change
2. Check if the app deploys and works
3. Logged into the instance and checked if the file `/var/log/make-swap-xvdc.log` was written.
4. Checked if the file content was as expected.
-------------
Check different environment configurations.
Test with a PHP app.

[FB-1599] Add detailed logging to swap creation

---

cookbooks/nodejs/attributes/default.rb

-------------
This PR updates to the latest Node.js versions.
-------------
Updates to the latest versions of Node.js.
Estimated risk
-------------
Low. just minor version bumps.
-------------
nodejs recipe
Dependencies
-------------
-------------
With a Ruby app.
Upgraded an existing environment and checked if nodejs was upgraded and deploys work.
Created a new environment with these changes and checked if a deploy works.
-------------
Test different app servers.

[FB-1766] Update Node.js versions

---

cookbooks/mysql/attributes/version.rb
cookbooks/mysql/recipes/install.rb

-------------
This PR updates the MySQL packages to the latest available versions.
-------------
Updates MySQL to the latest available versions
Estimated risk
-------------
Low. Just new versions added.
-------------
mysql recipes
Dependencies
-------------
None
-------------
1. Tested booting a new (staging) environment with a dev stack with these changes for both MySQL 5.6 and 5.7.
2. Tested upgrading existing MySQL 5.6 and 5.7 staging environments from stable-v6 to a stack with these changes (Manually updated to the latest MySQL version in db lock file).
-------------
Test different app servers.
Test a MySQL production configuration.

[TEY-125] Update MySQL to the latest available versions

---

cookbooks/postgresql/attributes/version.rb
cookbooks/postgresql/recipes/server_install.rb

-------------
This PR updates the PostgreSQL packages to the latest available versions.
-------------
Updates PostgreSQL to the latest available versions
Estimated risk
-------------
Low. Just new versions added.
-------------
postgresql recipes
Dependencies
-------------
None
-------------
1. Tested booting a new (staging) environment with a dev stack with these changes for PostgreSQL 9.5, 9.6, 10, and 11.
2. Tested upgrading existing PostgreSQL 9.5, 9.6, 10, and 11 staging environments from stable-v6 to a stack with these changes (Manually updated to the latest PostgreSQL version in db lock file).
-------------
Test different app servers.
Test a …

[TEY-126] Update PostgreSQL to the latest available versions

---

cookbooks/collectd/recipes/default.rb
cookbooks/collectd/templates/default/collectd.conf.erb

-------------
This PR fixes some inaccuracies in the collect.conf template around checks for DBs.
They were caused by the introduction of RDS Aurora support.
-------------
Improves the configuration of collect DB checks.
Estimated risk
-------------
Medium. No change in logic, just cleanup and more precise db stack checks.
-------------
collectd recipes
Dependencies
-------------
None
-------------
Tested environments with the following DB configurations
* EY PostgreSQL 11.x
* EY MySQL 5.7.x
* RDS PostgreSQL 10.x
* RDS MySQL 5.7.x
* RDS Aurora PostgreSQL 10.x
* RDS Aurora MySQL 5.6.x
For each configuration checked if the collectd.conf file was setup correctly.
------------- …

[TEY-148] Fix DB checks in collectd config

---

cookbooks/ey-lib/libraries/ey-environment.rb

This PR updates the minor versions of Ruby 2.4, 2.5, 2.6, and 2.7.
Updates to the latest available Ruby versions (2.4.10, 2.5.8, 2.6.6. and 2.7.1)
Medium. 
Minor ruby version bump
EngineYard Libraries (ey-lib)
Boot new stack -> new Ruby version used
Boot new stack w/jemalloc -> new Ruby w/jemalloc version used
Boot old stack -> upgrade -> new Ruby version used
Boot old stack w/jemalloc -> upgrade -> new Ruby w/jemalloc version used
Test different app server and DB configurations.

[TEY-243] update ruby version(s)

---

cookbooks/collectd/templates/default/collectd.conf.erb

-------------
This PR fixes PostgreSQL checkpoint alerts in the collect.conf.
-------------
Improves the configuration of collect checkpoint checks.
Estimated risk
-------------
Low.
-------------
collected recipes
Dependencies
-------------
None
-------------
PostgreSQL (10/11) on solo environment
PostgreSQL (10/11) on a clustered environment
-------------

[TEY-212] Fix postgresql checkpoint checks in collectd config

---

cookbooks/mysql/recipes/install.rb

Fixes URLS for percona 
Percona url fixes
High - affects MySQL install
MySQL
* Created fresh environment 
* Selected MySQL version
* Booted solo instance
* Checked chef ran successfully and MySQL was correct
* Booted multiple instances
* Checked chef ran successfully
* Checked MySQL version 
* Repeat of testing

[FB-4981] MySQL URL and Curl update

---

cookbooks/nginx/recipes/default.rb
cookbooks/nginx/templates/default/nginx_app.conf.erb

Fixes nginx upstream for puma
Puma workers fixed with nginx
Medium risk - Needs to be fixed and may effect nginx if not tested correctly
nginx 
nginx
* Booted an environment using puma
* Checked nginx configuration to make sure upstream is configured correctly 
* Booted an environment using passenger
* Checked nginx configuration to make sure nginx is good.
* Booted an environment using unicorn
* Checked nginx configuration to make sure correct number is configured 
**QA instructions**
* Boot multiple environments using a different stack e.g puma,unicorn, passenger
* Deploy an application
* Check nginx configurations.

[FB-3893] Fixes worker count for puma nginx

---

cookbooks/ey-lib/libraries/ey-environment.rb
cookbooks/ruby/recipes/default.rb

Updates ruby versions along with ruby-install
Ruby updated to latest versions along with method of install to support later ruby version
Estimated risk
High 
Ruby - Install
ey-environment - Ruby version

updates ruby and ruby-install

---

cookbooks/ey-lib/libraries/ey-environment.rb

This PR updates the minor versions of Ruby 2.5, 2.6, and 2.7.
Updates to the latest available Ruby versions (2.5.9, 2.6.7, 2.7.3, and 3.0.1(For UI release))
Medium. 
Minor ruby version bump
EngineYard Libraries (ey-lib)
Boot new stack -> new Ruby version used
Boot new stack w/jemalloc -> new Ruby w/jemalloc version used
Boot old stack -> upgrade -> new Ruby version used
Boot old stack w/jemalloc -> upgrade -> new Ruby w/jemalloc version used
Test different app server and DB configurations.

[FB7807] updated ruby versions

---

cookbooks/sidekiq/attributes/default.rb
cookbooks/sidekiq/readme.md
cookbooks/sidekiq/templates/default/sidekiq.yml.erb
custom-cookbooks/sidekiq/cookbooks/custom-sidekiq/attributes/default.rb

https://t3.fogbugz.com/f/cases/10195/Add-max_retries-to-sidekiq-configuration

[FBZ-10195] add max retries on sidekiq
